#######################################################################################
# Book settings
title: IBM Quantum Challengeで学ぶ量子コンピューティング
author: Quantum Tokyo
logo: ./resources/quantum-tokyo-icon.jpg
# Auto-exclude files not in the toc
only_build_toc_files: true
#######################################################################################
# Execution settings
execute:
  execute_notebooks: off
  exclude_patterns:
  - '*_bk*'

#######################################################################################
# LaTeX-specific settings
latex:
  latex_documents:
    targetname: book.tex

#######################################################################################
# Launch button settings
repository:
  url: https://github.com/quantum-tokyo/ibm-quantum-challenge-textbook # The URL to your book's repository
  path_to_book: "" # A path to your book's folder, relative to the repository root.
  branch: main # Which branch of the repository should be used when creating links (optional)

#######################################################################################
# HTML-specific settings
html:
  use_repository_button: true

#######################################################################################
# Parse and render settings
parse:
  myst_enable_extensions: # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
  - amsmath
  - dollarmath
